# Docker Compose Otimizado para Testes de Escalabilidade
version: '3.9'

services:
  servidor:
    image: ${DOCKERHUB_USER:-guimsk}/servidorCpp:latest
    container_name: servidor_app
    ports:
      - "5000:5000"
    environment:
      - SERVER_PORT=5000
      - MAX_CONNECTIONS=1000
      - THREADS_PER_CLIENT=1
    restart: unless-stopped
    networks:
      - scalability-network
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "5000"]
      interval: 10s
      timeout: 5s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          cpus: '0.5'
          memory: 1G

  cliente:
    image: ${DOCKERHUB_USER:-guimsk}/cliente:latest
    container_name: cliente_app
    environment:
      - SERVER_HOST=servidor
      - SERVER_PORT=5000
      - QTD_CLIENTES=10
      - MENSAGENS_POR_CLIENTE=1
      - TIMEOUT_CONEXAO=30
      - RESULTS_DIR=/app/results
    depends_on:
      servidor:
        condition: service_healthy
    volumes:
      - ./resultados:/app/results
    networks:
      - scalability-network
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          cpus: '0.25'
          memory: 512M

networks:
  scalability-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
    driver_opts:
      com.docker.network.bridge.name: scalability-br0
