# ============================================================================
# KUBERNETES SERVIDOR DEPLOYMENT - OTIMIZADO PARA START RÁPIDO
# Deployment e Service do servidor com otimizações de velocidade
# ============================================================================

apiVersion: apps/v1
kind: Deployment
metadata:
  name: servidor
  namespace: scalability-test
  labels:
    app: servidor
    component: scalability-test
spec:
  replicas: 2  # Valor inicial, será ajustado dinamicamente pelos testes
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: servidor
  template:
    metadata:
      labels:
        app: servidor
        component: scalability-test
    spec:
      # Otimizações para start rápido
      terminationGracePeriodSeconds: 5
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      containers:
      - name: servidor
        image: guimsk/servidor-cpp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          name: tcp-port
          protocol: TCP
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "1"
            memory: "1Gi"
        env:
        - name: PORT
          value: "5000"
        - name: MAX_CONNECTIONS
          value: "500"
        - name: THREADS_PER_CLIENT
          value: "1"
        # Probes otimizados para start rápido
        readinessProbe:
          tcpSocket:
            port: 5000
          initialDelaySeconds: 1
          periodSeconds: 1
          timeoutSeconds: 1
          failureThreshold: 2
        livenessProbe:
          tcpSocket:
            port: 5000
          initialDelaySeconds: 3
          periodSeconds: 3
          timeoutSeconds: 1
          failureThreshold: 3
        # Otimizações de recursos
        securityContext:
          runAsNonRoot: false
          allowPrivilegeEscalation: false
---
# Service otimizado para performance
apiVersion: v1
kind: Service
metadata:
  name: servidor-service
  namespace: scalability-test
  labels:
    app: servidor
    component: scalability-test
spec:
  selector:
    app: servidor
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: tcp-port
  type: ClusterIP
  sessionAffinity: None
